// Copyright (C) 2017 Schroedinger Entertainment
// Distributed under the Schroedinger Entertainment EULA (See EULA.md for details)

using System;
using System.Collections.Generic;

namespace SE.Hyperion.Desktop.Win32
{
    [Flags]
    public enum WinEventHookFlags : int
    {
        /// <summary>
        ///     The callback function is not mapped into the address space of the process that generates the
        ///     event. Because the hook function is called across process boundaries, the system must queue
        ///     events. Although this method is asynchronous, events are guaranteed to be in sequential order.
        /// </summary>
        WINEVENT_OUTOFCONTEXT = 0,

        /// <summary>
        ///     Prevents this instance of the hook from receiving the events that are generated by the thread that
        ///     is registering this hook.
        /// </summary>
        WINEVENT_SKIPOWNTHREAD = 1,

        /// <summary>
        ///     Prevents this instance of the hook from receiving the events that are generated by threads in this process.
        ///     This flag does not prevent threads from generating events.
        /// </summary>
        WINEVENT_SKIPOWNPROCESS = 2,

        /// <summary>
        ///     The DLL that contains the callback function is mapped into the address space of the
        ///     process that generates the event. With this flag, the system sends event notifications
        ///     to the callback function as they occur. The hook function must be in a DLL when this flag
        ///     is specified. This flag has no effect when both the calling process and the generating process
        ///     are not 32-bit or 64-bit processes, or when the generating process is a console application.
        /// </summary>
        WINEVENT_INCONTEXT = 4
    }
}
